### ISSUE TITLE
Not able to open the add cloud storage dialog

### ISSUE THREAD

**Issue by suvojit-0x55aa** [heartexlabs/label-studio#1039]
**Describe the bug**
When I click on the "Add Source Storage" and "Add Target Storage" the dialog box appears for few moment and closes.

**To Reproduce**
1. Go to 'Project > Setting > Cloud Storage'
2. Click on 'Add Source Storage'
3. Dialog box doesn't open

**Expected behavior**
Expect dialog box to open to add cloud storage

**Screenshots**
```
Uncaught (in promise) TypeError: v.map 
is not a function
    at StorageForm.js:51
    at ia (react-dom.production.min.js:157)
    at Ra (react-dom.production.min.js:176)
    at $l (react-dom.production.min.js:271)
    at Ts (react-dom.production.min.js:250)
    at js (react-dom.production.min.js:250)
    at Ss (react-dom.production.min.js:250)
    at gs (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Label Studio Version: 1.0.2

**Comment by makseq** [comment]
@suvojit-0x55aa We've fixed it in the latest master commits.

**Comment by suvojit-0x55aa** [comment]
@makseq is it available with docker-compose pull ?

**Comment by makseq** [comment]
I think yes

**Comment by suvojit-0x55aa** [comment]
@makseq tried pulling the latest image problem still persists.

**Comment by makseq** [comment]
@suvojit-0x55aa Could you show `/version` page?

**Comment by SMarwen** [comment]
Hello @suvojit-0x55aa 
Please try this command : `docker volume prune`

**Comment by suvojit-0x55aa** [comment]
@makseq Label Studio Version is at  v1.0.2

@SMarwen volume prune will just delete unused volumes right ?

**Comment by SMarwen** [comment]
yes exactly,
in this line here : https://github.com/heartexlabs/label-studio/blob/0c237b9318599339823e5f19ac30020796f20997/docker-compose.yml#L36
Label studio is linking the code to this volume
So if you used docker compose with previous version, you need to delete the volume and spin up the services again
I asked why they did it this way on slack, but I got no answer @makseq 
so in short, steps are :
- `docker-compose down`
- `docker volume prune`
- `docker-compose up`

**Comment by suvojit-0x55aa** [comment]
@SMarwen but wouldn't it delete the assets so I have to build the image again ?

**Comment by SMarwen** [comment]
@suvojit-0x55aa I am not sure tbh
may be you can delete one specific volume ?

**Comment by suvojit-0x55aa** [comment]
@SMarwen no that didn't solve it.
@makseq any updates on this ?

**Comment by makseq** [comment]
@suvojit-0x55aa Just checked it in the master branch, everything works ok. 
I think you could you the latest container from our dockerhub: heartexlabs/label-studio:latest

**Comment by SMarwen** [comment]
Hi @suvojit-0x55aa 
The root cause of the problem is that storages are not shown because of missing `return storage_list` in `label_studio/io_storages/all_api.py`, this bug was solved in recent versions.

In order to solve it, you should rebuild the image or download the latest docker image and make sure that `labela_studio_app` is using the latest image.

If you have built the container using the old version, then label_studio folder is still be linked to static volume, so changes in this folder will not be applied in the container, thus the bug will not be solved

To check this out you can do :

- `docker-compose up`
- `docker exec -it label-studio_app_1 bash`
- `ll`

Finally the steps become :

- `docker-compose down`
- `docker volume prune`
- `docker build -t . heatexlabs/label-studio:latest .`
- `docker-compose up`

Of course docker volume prune is here to delete old volumes and hence old code

**Comment by suvojit-0x55aa** [comment]
@makseq after downloading the latest dockerhub image I get the following error on the app:
```
app_1    | => Run bash label-studio...
app_1    | /usr/local/bin/label-studio: line 3: __requires__: command not found
app_1    | /usr/local/bin/label-studio: line 4: import: command not found
app_1    | /usr/local/bin/label-studio: line 5: import: command not found
app_1    | /usr/local/bin/label-studio: line 6: from: command not found
app_1    | /usr/local/bin/label-studio: label-studio: line 9: syntax error near unexpected token `('
app_1    | /usr/local/bin/label-studio: label-studio: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'
```

**Comment by suvojit-0x55aa** [comment]
Deleted older repo, exported data with a fresh build, it worked.
