### ISSUE TITLE
Export annotations for local dataset and reimport them in a fresh label studio creates duplicates

### ISSUE THREAD

**Issue by gregor-mittag** [heartexlabs/label-studio#1165]
Dear label-studio team,

I have come across an issue of which I am not sure about how to classify it.
I would say label-studio does not behave according to my expectations, which can be one of two things:
A bug in label-studio or a bug in my expectations:

When I have an instance of label-studio running on localhost and I have also added the local storage as cloud storage I experience the following:

1. Two people are working on two instances where the local storage directory structure is identical, i.e. they have the same local datasets.
1. Then I want to import the annotations of one person to the label studio instance of the other person.
1. Since both have the same local data, syncing the local storage leads to the same annotation tasks.
1. The first person exports the data in JSON format.
1. The second person imports the JSON file and the annotated tasks are correctly listed, but in addition the same tasks exist without annotations.

My expectation was that label-studio detects that and just adds the annotations.
Or is using the import function not the right way to go here?

Best regards,
Gregor

**Comment by makseq** [comment]
@gregor-mittag could you check the latest commits from master? Hope it's fixed now.

**Comment by gregor-mittag** [comment]
@makseq thanks for taking care of my issue!
However, I am currently on vacation without access to my computer. I will check when I am back in 2 weeks.

**Comment by gregor-mittag** [comment]
Back from vacation!
@makseq when you ask me to check the latest commits from master, do you mean to follow the instructions here? https://github.com/heartexlabs/label-studio#install-for-local-development
Or are there some pre-releases or nightly releases available?

**Comment by makseq** [comment]
@gregor-mittag Hope you had a lovely vacation :slightly_smiling_face: ! 
Yes, I meant those instructions. We put the latest versions (similar to nightly builds) into the master branch. 
Have you tried it already?

**Comment by gregor-mittag** [comment]
@makseq Thanks for the confirmation!
I tried it with the master branch (commit ID: 0e5536602c1b96489028dcb9a65471c0a903bbde).
However, the issue is still the same:

I first set up the local storage and synced it leading to the following result:
![grafik](https://user-images.githubusercontent.com/82151898/130026441-a979fd90-9269-47b1-af6d-0ec93cb2957d.png)

After importing the JSON file with 42 annotations, I get the following:
![grafik](https://user-images.githubusercontent.com/82151898/130026864-fe8d8af3-1474-4c72-b02e-fa4bdf26644a.png)

Unfortunately, I cannot send you the data and annotations to try it out yourself.
Do you have an idea on how to create a minimal example?

**Comment by niklub** [comment]
Hi, @gregor-mittag ! I think you're trying to import 42 annotations separately from the 121 tasks created from the bucket sync. When importing data, every JSON item creates new tasks disregarding any existence. Therefore, it sums up to 163 tasks in total, which is expected.
In case you want to attach annotations to already created tasks, I suggest you might try using [the API](https://labelstud.io/api/#operation/api_tasks_annotations_create), [collecting corresponding tasks IDs](https://labelstud.io/api/#operation/api_projects_tasks_list) beforehand.
Tell me if I'm missing something, and glad to help you further.

**Comment by gregor-mittag** [comment]
@niklub I think your guess is correct.
I was actually hoping to get this task done without writing some script, but it seems to me that it shouldn't be too complicated to do so.
I'll reopen this issue if I run into problems.

Thanks, @makseq, @niklub for your help and suggestions!
