### ISSUE TITLE
Changing a choice with children/nested choices does not clear the child choices

### ISSUE THREAD

**Issue by filpano** [heartexlabs/label-studio#3859]
**Describe the bug**
I have the following situation:

```
- Choice A
  - Choice A1
  - Choice A2
- Choice B
  - Choice B1
  - Choice B2
```

A1, A2 and B1, B2 are only active, selectable and viewable when A or B respectively is selected.

Then, if I label my as follows:

```
A -> A1 -> B
```

I have both choice `B` and `A1` active, which should not be possible normally. This is because the children of choices are not cleared when the parent is.

Is there are workaround for this behaviour?  

**To Reproduce**
The following labeling config can reproduce this behaviour:

```
<View style="box-shadow: 2px 2px 5px #999;                padding: 20px; margin-top: 2em;                border-radius: 5px;">
    
  <Table name="table" value="test"/>

  <Choices name="level1" toName="table" choice="single-radio" showInLine="true" required="true">
    <Choice value="A"/>
    <Choice value="B"/>
  </Choices>
  
  <View visibleWhen="choice-selected" whenTagName="level1" whenChoiceValue="A">
    <Choices name="level2_A" toName="table" choice="single-radio" showInLine="true" visibleWhen="choice-selected" required="true" whenTagName="level1" whenChoiceValue="A">
      <Choice value="A1"/>
      <Choice value="A2"/>
    </Choices>
  </View>

  <View visibleWhen="choice-selected" whenTagName="level1" whenChoiceValue="B">
    <Choices name="level2_B" toName="table" choice="single-radio" showInLine="true" visibleWhen="choice-selected" required="true" whenTagName="level1" whenChoiceValue="B">
      <Choice value="B1"/>
      <Choice value="B2"/>
    </Choices>
  </View>
  
</View>
```

**Expected behavior**
In the above example, I would expect that changing the choice from `A` to `B` would clear the `A1` child choice.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - Label Studio Version 
```json
{
  "release": "1.5.0dev",
  "label-studio-os-package": {
    "version": "1.5.0dev",
    "short_version": "1.5",
    "latest_version_from_pypi": null,
    "latest_version_upload_time": null,
    "current_version_is_outdated": false
  },

  "label-studio-os-backend": {},

  "label-studio-frontend": {
    "message": "feat: DEV-388: Introducing default attributes for AudioPlus (#818)  *  ...",
    "commit": "c0ff3e48032c3ab77c51835c632768b72730eecb",
    "branch": "master",
    "date": "2022-09-12T15:24:05Z"
  },

  "dm2": {
    "message": "feat: DEV-1752: Support links to drafts and annotations (#101)  * Supp ...",
    "commit": "72105e4385620cf4a59b5bd3e68adca19287bf8b",
    "branch": "master",
    "date": "2022-09-02T18:15:25Z"
  },

  "label-studio-converter": {
    "version": "0.0.44"
  }
}
```

**Comment by hlomzik** [comment]
Hi! What's the problem do you have exactly? How do you know that A1 is still selected?

If you submit your data you'll get only B in result, A1 is hidden and skipped from result. If that's not your case, what version do you use? We had some problems with nested choices, but they were fixed a long time ago.

Sorry, missed version. Most probably you have a bug that was fixed, so update LS.

**Comment by yeli-sibat** [comment]
I have tried v1.15.0. It is not fixed. It behaves differently compared to the playground. In the playground I did observe that the down layers were unselected when the upper layers were changed. However in my own deployment I have observed that those downstream choices werenot removed.

**Comment by hlomzik** [comment]
@yeli-sibat can you please record a video so I'll understand the problem better? You can't see A1 if you selected B, so is this the problem that you see it? Or you don't like that if you jump between A and B this A1 choice is still selected?

**Comment by yeli-sibat** [comment]
First of all, thank you for your reply. I have deloyed another isntance of v1.19 and problem solved. So this should have been fixed between v1.15.0 to v1.19 (at least to my case).

Allow me to summarize the problem I have encountered. Following is the xml of my labeling settings. This is a three-layer choices structure as:

- A
- - Aa
- - - Aa1
- - - Aa2
- - - ...
- - Ab
- - Ac
- - - Ac1
- - - ...
- B
- -Ba
- - - Ba1
- - - ...
- -Bb
- - - Bb1
- - - ...

Basically it can be treated as a tree and my expected behavior is that only one leaf node can be selected. For example, "B-Ba-Ba2" and "A-Ab" are validated.  None leaf node selection is prohibited such as "B-Ba" is not allowed.


However, in the v1.15.0 verison, I have encountered the major problem: it does not seem to unselect the LEVEL-3 choice when the LEVEL-1 choice is switched. 

For example, at the first step, I have chosen A-Aa-Aa1
![Image](https://github.com/user-attachments/assets/6cd7b486-fd3d-423d-bc6a-14aad96e45f2)

At the second step, I have chosen B-Ba. However as we can see in the screenshot, the select of Aa1 was not cleared. 

![Image](https://github.com/user-attachments/assets/4c710976-5850-4477-b1ba-52455ed9c24f)

It also caused a problem in the exported json of the labeling result. The choices of Aa and Aa1 were there though the choice of A was gone. 

![Image](https://github.com/user-attachments/assets/d411067f-0605-4775-a8d5-6efbe1c86a41)

This behavior does not appear in v1.19. I have tried and in the newer version, the choices of children levels will be cleared when the choice of paraent level has been changed.

```
<View>
  
  <Header value="Test"/>
 <Text name="text" value="$text"/>
  
  <Header value="Please select LEVEL ONE"/>
<Choices name="LEVEL-ONE" toName="text" layout="select" required="true">
<Choice value="A" />
<Choice value="B" />
</Choices>
<View visibleWhen="choice-selected" whenTagName="LEVEL-ONE" whenChoiceValue="A">
<Header value="Please choose A LEVEL-TWO"/>
<Choices name="A-LEVEL-TWO" toName="text" layout="select" required="true" whenTagName="LEVEL-ONE" whenChoiceValue="A">
<Choice value="Aa" />
<Choice value="Ab" />
<Choice value="Ac" />
</Choices>
</View>
<View visibleWhen="choice-selected" whenTagName="LEVEL-ONE" whenChoiceValue="B">
<Header value="Please choose B LEVEL-TWO"/>
<Choices name="B-LEVEL-TWO" toName="text" layout="select" required="true" whenTagName="LEVEL-ONE" whenChoiceValue="B">
<Choice value="Ba" />
<Choice value="Bb" />
<Choice value="Bc" />
<Choice value="Bd" />
</Choices>
</View>
<View visibleWhen="choice-selected" whenTagName="A-LEVEL-TWO" whenChoiceValue="Aa">
<Header value="Please choose Aa LEVEL-THREE"/>
<Choices name="A-Aa-LEVEL-THREE" toName="text" layout="select" required="true" whenTagName="A-LEVEL-TWO" whenChoiceValue="Aa">
<Choice value="Aa1" />
<Choice value="Aa2" />
<Choice value="Aa3" />
</Choices>
</View>
<View visibleWhen="choice-selected" whenTagName="A-LEVEL-TWO" whenChoiceValue="Ac">
<Header value="Please choose Ac LEVEL-THREE"/>
<Choices name="A-Ac-LEVEL-THREE" toName="text" layout="select" required="true" whenTagName="A-LEVEL-TWO" whenChoiceValue="Ac">
<Choice value="Ac1" />
<Choice value="Ac2" />
<Choice value="Ac3" />
<Choice value="Ac4" />
</Choices>
</View>
<View visibleWhen="choice-selected" whenTagName="B-LEVEL-TWO" whenChoiceValue="Ba">
<Header value="Please choose Ba LEVEL-THREE"/>
<Choices name="B-Ba-LEVEL-THREE" toName="text" layout="select" required="true" whenTagName="B-LEVEL-TWO" whenChoiceValue="Ba">
<Choice value="Ba1" />
<Choice value="Ba2" />
<Choice value="Ba3" />
<Choice value="Ba4" />
<Choice value="Ba5" />
</Choices>
</View>
<View visibleWhen="choice-selected" whenTagName="B-LEVEL-TWO" whenChoiceValue="Bb">
<Header value="Please choose Bb LEVEL-THREE"/>
<Choices name="B-Bb-LEVEL-THREE" toName="text" layout="select" required="true" whenTagName="B-LEVEL-TWO" whenChoiceValue="Bb">
<Choice value="Bb1" />
<Choice value="Bb2" />
<Choice value="Bb3" />
<Choice value="Bb4" />
<Choice value="Bb5" />
<Choice value="Bb6" />
</Choices>
</View>

</View>
```

**Comment by hlomzik** [comment]
Ah yes, thank you for detailed explanation! Two-levels nested choices were working good for a while, but we realized that it's broken with deeper nesting. And we fixed it quite recently: https://github.com/HumanSignal/label-studio/pull/7180
I hope we won't find any critical issues in this part of Label Studio!

**Comment by yeli-sibat** [comment]
Yes it works exactly the way I have expected. Thank you so much. Appreciated for your help :)
