### ISSUE TITLE
Unable to see completions when resuming project 

### ISSUE THREAD

**Issue by vinayex2** [heartexlabs/label-studio#486]
Hi All,

I started a labeling project and completed around 150 tasks. When i resumed the project with label-studio start project_dir, i cannot see the previous completions. (pic attached)

However, I can download/export them.

The labeling IDs have also started from the bottom (so instead of 1,2,3,4... and so on, i get a new task ID that starts with one more than the number of tasks (pic attached)

**Label Studio version**: 0.7.5.post2
Python 3.8.5 (Anaconda)

![annotation_resume_issue](https://user-images.githubusercontent.com/577743/98512067-ad67ed80-228b-11eb-8fcb-4d172eec79cc.PNG)
![annotation_resume_issue_2](https://user-images.githubusercontent.com/577743/98512073-b062de00-228b-11eb-99ad-e2f7b2db5266.PNG)

**Comment by makseq** [comment]
@vinayex2 Did you change anything inside of `project_dir` manually?

**Comment by makseq** [comment]
@vinayex2 Also you may try to upgrade to 0.8.0, it seems we've fixed something like this in this version

**Comment by tlaud** [comment]
In my setup, the problem of disappearing completions also exists. I discovered that there is a difference between
`label-studio start project_dir` 
and 
`label-studio start ./project_dir`

When one of the options leads to disappearing completions, the other works.

Maybe this serves as work around.

**Comment by makseq** [comment]
@vinayex2 Do you have this bug on new LS versions (e.g. 0.8.2)?

**Comment by makseq** [comment]
Feel free to reopen if problem is still persistent.

**Comment by atreyasha** [comment]
I am still experiencing this issue in `v1.4.0` of the community edition. I launch `label-studio` via the basic `docker` method (not `docker-compose`). Is anyone else still experiencing this as well?
