### ISSUE TITLE
Removed whitespaces from annotated text

### ISSUE THREAD

**Issue by keren42** [heartexlabs/label-studio#5338]
**Describe the bug**
Text annotations: in some locations in my raw text, there are extra whitespaces instead of a single whitespace.
In the display screen, it doesn't show them, and displays only a single space.
Additionally, in the output JSON I export, the text content is displayed without extra whitespaces, while the start and end indexes are aligned with the indexes of the original text (with the extra spaces).

**To Reproduce**

For the text:

4   cm

I would get this in the json file:

          "value": {
            "start": 0,
            "end": 7,
            "text": "4 cm",
            "labels": [
              "Size"
            ]
          },

While I expect this:

          "value": {
            "start": 0,
            "end": 7,
            "text": "4   cm",
            "labels": [
              "Size"
            ]
          },

With the extra spaces. The indices are consistent with the extra whitespaces, and the text field (and presented text in the platform) are not.

**Environment (please complete the following information):**
 - OS: Windows 10 enterprize
 - Label Studio Version 1.7.0

**Comment by hogepodge** [comment]
Thanks for your report, this looks like it might be a bug, but can you upgrade to the latest version of label studio? We don't have long-term support for previous releases, and this issue might have been fixed in the current release.

**Comment by hlomzik** [comment]
Hey! That's expected behaviour in general, because we render text as html, so spaces are glued together, however that's a good question on how it should be reflected in the result — we'll take a look.

To fix the behaviour and view you can add `<Style>.htx-text{ white-space: pre-wrap; }</Style>` to your config like it's suggested on our doc page: https://labelstud.io/tags/text

**Comment by yanwenjie1** [comment]
I have the same problem, which is caused by multiple consecutive spaces.
My solution is to use regular expressions and replace \s+with \s

**Comment by KensingtonOscupant** [comment]
Using `<Style>.htx-text{ white-space: pre-wrap; }</Style>` doesn't fix it for me either. 

Maybe I'm doing it wrong, but you're supposed to add the style line at the top of the main view, right? This is the start of my config

```
<View>
    <Style>.htx-text{ white-space: pre-wrap; }</Style>
    <Text name="text" value="$text"/>

    <!-- NER Labels for annotating sentences -->
    <Labels name="label" toName="text">
        <Label value="label 1"/>
        <Label value="label 2"/>
```
