### ISSUE TITLE
CORS and URL Resolution Issue in Audio File Loading

### ISSUE THREAD

**Issue by abdulazizbek711** [heartexlabs/label-studio#7103]
There was an issue loading URL from $audio value

Things to look out for:

URL is valid
URL scheme matches the service scheme, i.e. https and https
The static server has wide-open CORS, [more on that here](https://labelstud.io/guide/storage.html#Troubleshoot-CORS-and-access-problems)
Technical description: HTTP error status: 0
UrL:................................................................................, i am getting this error after synching data from s3 source storage, and clicking on the task, 

and i checked developer's console also:

 A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request.

To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.

Note that if an opaque response is sufficient, the request's mode can be set to no-cors to fetch the resource with CORS disabled; that way CORS headers are not required but the response content is inaccessible (opaque).

pls, help me with this issue. Its too urgent

**Comment by heidi-humansignal** [comment]
Hello,
Based on the error message and the console output, it appears that Label Studio is unable to load your audio file because the CORS headers in the response are either missing or invalid. Here are a few steps to help resolve the issue:

1. **Enable Pre-Signed URLs:**

In your S3 source storage settings, ensure that the option to "Use pre-signed URLs" is enabled. This tells Label Studio to generate temporary HTTPS URLs that bypass direct “s3://” access, which browsers cannot handle directly.
2. **Verify S3 Bucket CORS Configuration:**

Make sure your S3 bucket’s CORS policy allows requests from your Label Studio domain. A typical S3 CORS configuration that works well with Label Studio looks like this:

    [{ "AllowedHeaders": ["*"], "AllowedMethods": ["GET", "HEAD"], "AllowedOrigins": ["*"], "ExposeHeaders": [] } ]

If you need a more restricted setup, ensure that the `AllowedOrigins` exactly match your Label Studio instance’s URL and that only required methods (usually GET and HEAD) are allowed.

1. **Confirm the URL Format:**

Check that your tasks are referencing the generated HTTPS URL rather than a raw “s3://” URL. The pre-signed URL should begin with “https://” and resolve properly when pasted into a browser.
2. **Inspect Response Headers:**

Use your browser’s developer console to inspect the network requests for the audio file. Confirm that the response includes the necessary CORS headers (especially `Access-Control-Allow-Origin`). If the header is missing, the bucket’s CORS configuration may need further adjustment.
3. **IAM Permissions:**

Verify that your S3 bucket’s IAM policies include the proper permissions (such as `s3:GetObject`) so that Label Studio can access the files.
For further details on how to configure your CORS settings, please refer to our troubleshooting guide here: Troubleshoot CORS and Access Problems.
Could you please verify these settings on your end and let me know if the issue persists after making the adjustments? If you have any additional details from the console or network tab (such as specific headers returned with the preflight request), feel free to share them.


Thanks,

Tyler Conlee
Head of Support
HumanSignal

> Comment by Tyler Conlee
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/13396967663)

**Comment by abdulazizbek711** [comment]
hello, i did [{ "AllowedHeaders": ["domain name"], "AllowedMethods": ["GET", "HEAD"], "AllowedOrigins": ["*"], "ExposeHeaders": [] } ] cors policy, i confirmed url format, it starts with https://, in IAM policies also. i configured appropriate actions, methods. but having same error as I shared previously

**Comment by abdulazizbek711** [comment]
![Image](https://github.com/user-attachments/assets/89b3fdbf-d443-44bf-ac12-e5efff977569)


![Image](https://github.com/user-attachments/assets/c29f4a15-fbcc-475b-aad5-30a2bd8238d4)

these are the actual IAM policy and cors settings that I have currently

**Comment by oliverdain** [comment]
I'm seeing something very similar but for videos. Oddly the preview loads and plays find if I click the "click to load" button in the data overview. However, when it loads the labeling interface videos don't load and developer tools shows CORS errors. I can't figure out why it'd work to load the video preview but not the video in the player interface. In my case I'm using GCS but I'm fairly sure I have it all configured correct. See screen shots, etc. below:

![Image](https://github.com/user-attachments/assets/943e2a85-dd96-4872-96f5-d40b55699b1e)

Previewing the video works:

![Image](https://github.com/user-attachments/assets/2566ce62-fb1c-421f-a6eb-051fb5ef03af)

But things fail in the labeling interface (here I'm just using the existing object detection for video template):

![Image](https://github.com/user-attachments/assets/3109bb7b-b80e-49bf-9918-d061a0740f0c)

The configuration appears to be correct:

```bash
$ gcloud storage buckets describe gs://companionpro-main-labels
cors_config:
- maxAgeSeconds: 3600
  method:
  - GET
  origin:
  - '*'
  responseHeader:
  - Content-Type
  - Access-Control-Allow-Origin
creation_time: 2024-02-05T21:21:34+0000
default_storage_class: STANDARD
generation: 1707168094839763927
labels:
  purpose: ml_labeling
location: US-CENTRAL1
location_type: region
metageneration: 7
name: companionpro-main-labels
public_access_prevention: enforced
soft_delete_policy:
  effectiveTime: '2024-03-01T08:00:00+00:00'
  retentionDurationSeconds: '604800'
storage_url: gs://companionpro-main-labels/
uniform_bucket_level_access: false
update_time: 2024-02-05T23:37:16+0000
versioning_enabled: true
```

I see this with both versions 1.15 and 1.16 of Label Studio.

**Comment by oliverdain** [comment]
I think I figured out the problem. The preflight request from Label Studio includes `Access-Control-Request-Headers: baggage,sentry-trace` which doesn't seem correct. If I test this on the command line using curl I get an `Access-Control-Allow-Origin: *` response if I omit the `Access-Control-Request-Headers` and I do *not* get the allow-origin response if I include it. I can reconfigure my bucket to allow those headers but (1) the Label Studio documentation does not say to do this and (2) I think it's a bug to be sending those.

A little web search indicates that maybe the bug is related to this bug reported on Sentry: https://github.com/getsentry/sentry-javascript/issues/5868

**Comment by heidi-humansignal** [comment]
Hello,

Thank you for the additional information. As a workaround can you please modify the GCS bucket CORS policy to explicitly allow the extra headers (`baggage,sentry-trace`) in `AllowedHeaders   `This should help resolve the CORS error quickly while also pushing for a more permanent fix!

    [{ "AllowedHeaders": ["*", "baggage", "sentry-trace"], "AllowedMethods": ["GET", "HEAD"], "AllowedOrigins": ["*"], "ExposeHeaders": [] }]

> Comment by Oussama Assili
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/13566622693)

**Comment by oliverdain** [comment]
@heidi-humansignal thanks. Yes, I did that a while back and it's an effective workaround.

**Comment by heidi-humansignal** [comment]
Great! happy that you were unblocked while we are pursuing a permanent fix!

Please feel free to contact us if you have additional questions!

> Comment by Oussama Assili
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/13586789348)

**Comment by 106firestarter** [comment]
hey, just wanted to emphasize that a permanent fix is very much welcomed!

thank you for the support !

**Comment by 106firestarter** [comment]
nothing to address this on the latest update right?
it's a bit disappointing because we're still on <1.14 to cope with this...

**Comment by makseq** [comment]
I hope this will be the permanent solution - https://github.com/HumanSignal/label-studio/pull/7528. 

Sentry added the Baggage header to Presigned URLs that LS generates (/tasks/*/presign, /tasks/*/resolve, /projects/*/presign, /projects/*/resolve). It changed the signature for presigned URLs and they threw CORS errors. Now it's fixed in Sentry.ts on the frontend.

**Comment by 106firestarter** [comment]
Still not working. This is very weird, just having this issue with the labeling interface it self because I'm able to load the same audio with the previews in the dataset entries list but just not on the labeling interface where the audio is loaded.
