### ISSUE TITLE
Brush label mouse over duplicate region in the canvas

### ISSUE THREAD

**Issue by toddmccolloughellumen** [heartexlabs/label-studio#7654]
**Describe the bug**
We create a brush label. When we mouse over the region for the brush label we see a duplicate region in the canvas. When we mouse away from the region for the brush label we see only the real region and the duplicate region goes away.

**To Reproduce**
1. Set up a project with brush labels.
2. Label a region.
3. Mouse over the region in the Regions tab in the side-bar to see the duplicate mask.
4. Mouse away from the region in the Regions tab in the side-bar to remove the duplicate mask and only see the real mask.

**Expected behavior**
Regardless of mouse over in the Regions tab there should be no duplication of brush labels.

**Screenshots**

How it should look without duplication
![Image](https://github.com/user-attachments/assets/39febd05-3e8e-4195-87e7-6a484573790a)

How it looks on mouse over with duplication

![Image](https://github.com/user-attachments/assets/393757c4-b47d-4c8d-9ae9-6b55476e916a)

https://github.com/user-attachments/assets/a3d3c248-5b2a-428f-b0f3-cb5af61d7d39

**Environment (please complete the following information):**
Seen on multiple environments

OS: hosted on Linux Ubuntu 22.04.4 LTS (GNU/Linux 6.8.0-1029-aws x86_64) VM, viewing on Windows/Edge and Mac/Safari.
Label Studio Version 1.17

OS: hosted on Windows Server 2025 Datacenter 10.0.26100 VM, viewing on Windows/Edge, Windows/Chrome, and Windows/Firefox and Mac/Safari.
Label Studio Version 1.17/1.18/1.19

**Comment by heidi-humansignal** [comment]
Hello,

Do you mind upgrading LS to 1.19 and see if you can see this behaviour?

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/15568682238)

**Comment by toddmccolloughellumen** [comment]
Hi I upgraded LS to 1.19 and still see the issue as reported above, thanks

**Comment by heidi-humansignal** [comment]
Hello,

Do you have any ml-backend connected? Is there interactive view all enabled? I'm having hard time reproducing this issue.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/15879576858)

**Comment by toddmccolloughellumen** [comment]
Hi

This was reproduced both with and without an ml-backend connected so it does occur without any ml-backend and interactive view. Primarily do use an ml-backend and an interactive view though for the use case.

This issue does not happen on every single system and computer tested. It happens on some but not on others. It has been since on viewing on Windows/Edge and Mac/Safari but other systems that have Windows/Edge or Windows/Chrome it is not reproducible on.

**Comment by heidi-humansignal** [comment]
Hello,

Ahh, yes, I've been using chrome and tried it on Firefox as well and its doesn't happen. We do recommend chrome as browser. Safari and Edge are not really supported as of yet.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/16186930566)

**Comment by toddmccolloughellumen** [comment]
Hi so it was not originally reported in the issue above as being a problem in Windows/Chrome and Windows/Firefox but the issue does happen there as well.

Again this issue does not happen on every single system and computer tested. But I do actually have at least one Windows system where the issue DOES happens in Windows/Chrome, Windows/Edge, and Windows/Firefox. I have updated the original issue above to reflect this.

**Comment by heidi-humansignal** [comment]
Hello,

The systems is the VM you are testing it on? Ubuntu that has windows VM for one of the system and the other is window server and VM is on it?

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/16333557988)

**Comment by toddmccolloughellumen** [comment]
Hi yes, the servers hosting label studio in this case are VMs in AWS EC2.

**Comment by heidi-humansignal** [comment]
Hello,

Can you upgrade to version 1.20 and see if its happening. There has been some bug fixes and that should be fixed now.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/17270682249)

**Comment by toddmccolloughellumen** [comment]
> Hello,
> 
> Can you upgrade to version 1.20 and see if its happening. There has been some bug fixes and that should be fixed now.
> 
> Thank you, Abu
> 
> > Comment by Abubakar Saad
> > [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/17270682249)

Hi

Thanks for the update. Upgraded to version 1.20. Unfortunately continue to see the same issue with duplicate region in the canvas as reported in this thread so does not appear to have fixed it.

**Comment by heidi-humansignal** [comment]
Hello,

Do you mind sharing labeling interface? We are having hard time reproducing this.

Thank you,
Abu

> Comment by Abubakar Saad
> [Workflow Run](https://github.com/HumanSignal/label-studio/actions/runs/17768574176)

**Comment by szuhow** [comment]
It happens to me also (BrushLabels) - on Edge/Safari (Mac), but not on Firefox (Ubuntu).

**Comment by mpesavento** [comment]
I just migrated to 1.23.0 and i'm still seeing this behavior on Chrome 149.0.7827.116. Same experience on a naive Safari.
It appears to be downsampling (or expanding?) the hover buffer by 2x, shifting everything down, to the left, and double the size.

<img width="649" height="617" alt="Image" src="https://github.com/user-attachments/assets/1c9360ff-0b75-4b79-9762-439a1f25bf25" />
